{
 "title": "sysload dashboard",
 "description": "basic dashboard for sysload exporter",
 "tags": [ "sysload" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(sysload_sysload,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "sysload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "sysload",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sysload_sysload_one{instance=\"$instance\"}",
     "legendFormat": "sysload one"
    },
    {
     "expr": "sysload_sysload_five{instance=\"$instance\"}",
     "legendFormat": "sysload five"
    },
    {
     "expr": "sysload_sysload_fifteen{instance=\"$instance\"}",
     "legendFormat": "sysload fifteen"
    }
   ]
  },
  {
   "title": "interrupted cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sysload_si_cpu{mode=\"intr\",instance=\"$instance\"}",
     "legendFormat": "intr"
    },
    {
     "expr": "sysload_si_cpu{mode=\"sintr\",instance=\"$instance\"}",
     "legendFormat": "sintr"
    },
    {
     "expr": "sysload_si_cpu{mode=\"nice\",instance=\"$instance\"}",
     "legendFormat": "nice"
    },
    {
     "expr": "sysload_si_cpu{mode=\"system\",instance=\"$instance\"}",
     "legendFormat": "system"
    },
    {
     "expr": "sysload_si_cpu{mode=\"user\",instance=\"$instance\"}",
     "legendFormat": "user"
    },
    {
     "expr": "sysload_si_cpu{mode=\"wio\",instance=\"$instance\"}",
     "legendFormat": "wio"
    }
   ]
  },
  {
   "title": "io util",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sysload_io_util{instance=\"$instance\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "proc ctxt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sysload_proc_ctxt{instance=\"$instance\"}",
     "legendFormat": "proc_ctxt"
    }
   ]
  },
  {
   "title": "proc intr",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sysload_proc_intr{instance=\"$instance\"}",
     "legendFormat": "proc_intr"
    }
   ]
  }
 ]
}