{
 "title": "Systemd Resolved Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(systemd_resolved_transactions_total,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Cache Hit Rate",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(systemd_resolved_cache_hits_total{instance=\"[[instance]]\"}[$__rate_interval])",
     "legendFormat": "Cache Hits"
    },
    {
     "expr": "rate(systemd_resolved_cache_misses_total{instance=\"[[instance]]\"}[$__rate_interval])",
     "legendFormat": "Cache Misses"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(systemd_resolved_cache_hits_total{instance=\"[[instance]]\"}[$__rate_interval]) / (\nrate(systemd_resolved_cache_hits_total{instance=\"[[instance]]\"}[$__rate_interval]) + rate(systemd_resolved_cache_misses_total{instance=\"[[instance]]\"}[$__rate_interval])\n)",
     "legendFormat": "Cache Hit Rate"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(systemd_resolved_cache_hits_total{instance=\"[[instance]]\"}[$__rate_interval])",
     "legendFormat": "Cache Hits"
    }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(systemd_resolved_cache_misses_total{instance=\"[[instance]]\"}[$__rate_interval])",
     "legendFormat": "Cache Misses"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(systemd_resolved_transactions_total{instance=\"[[instance]]\"}[$__rate_interval])",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "Current Cache Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "systemd_resolved_current_cache_size{instance=\"[[instance]]\"}",
     "legendFormat": "Current Cache Size"
    }
   ]
  },
  {
   "title": "DNSSEC Verdicts",
   "type": "graph",
   "description": "note:make sure gather-dnssec option is enabled",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(systemd_resolved_dnssec_bogus_total{instance=\"[[instance]]\"}[$__rate_interval])",
     "legendFormat": "Bugus"
    },
    {
     "expr": "rate(systemd_resolved_dnssec_insecure_total{instance=\"[[instance]]\"}[$__rate_interval])",
     "legendFormat": "Insecure"
    },
    {
     "expr": "rate(systemd_resolved_dnssec_secure_total{instance=\"[[instance]]\"}[$__rate_interval])",
     "legendFormat": "Secure"
    },
    {
     "expr": "rate(systemd_resolved_dnssec_indeterminate_total{instance=\"[[instance]]\"}[$__rate_interval])",
     "legendFormat": "Indeterminate"
    }
   ]
  }
 ]
}